package com.switchfully.eurder.model.users.security;

public enum Feature {
    GET_ALL_USERS, GET_ALL_USERS_BY_USERTYPE, CREATE_ADMIN, GET_CUSTOMER_BY_ID, CREATE_ITEM, UPDATE_ITEM,
    GET_ALL_ITEMS_BY_STOCK_LEVEL, GET_ALL_ITEMS_SORTED_BY_STOCK_LEVEL, CREATE_ORDER,GET_ALL_ORDERS_BY_CUSTOMER_ID,
    GET_ALL_ORDERS
}
